import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google'
import Footer from "./components/Footer/Footer";
import NavBar from "./components/NavBar/NavBar";
import { AppProvider } from "./context/AppContext";
import CartContainer from "./components/CartContainer";

import PageTransition from "./components/PageTransition";
const nunito = Nunito({ weight: ["300", "400", "700"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: "birthblessing",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html className="scroll-smooth" lang="en">
      <body
        className={`${nunito.className} antialiased`}
      >
        <AppProvider>
          <NavBar />
          <CartContainer />
          <PageTransition>
            {children}
          </PageTransition>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
